title: "Bike Financing" # the name of your site, e.g. ACME Corp.
tagline: "Finance an electric bike"
email: your.email@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Add description here
author: name
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: UA-111111111-1
twitter:
  username: 
  card: summary #keep this to generate a twitter share card
permalink: pretty


# Build settings
plugins:
  - jekyll-feed
  - jekyll-airtable
  - jekyll-money
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank

airtable:
  enable_sync: true
  base_uid: 'appQDiGy9oyBWoqcC'
  tables:
    - name: 'Electric Bikes' 
    - name: 'Discounts'

collections_dir: collections
collections:
  electric_bikes:
    output: true
  discounts:
    output: true

sass:
  sass_dir: assets/css

defaults:
  - scope:
      type: "electric_bikes"
    values:
      layout: "bikes" # any jekyll layout file you already have in the _layouts that you want to use for this collection type.
      
compress_html:
  clippings: all
  comments:
    - '<!-- '
    - ' -->'
  endings:
    - html
    - head
    - body
    - li
    - dt
    - dd
    - rt
    - rp
    - optgroup
    - option
    - colgroup
    - caption
    - thead
    - tbody
    - tfoot
    - tr
    - td
    - th
  profile: false
  blanklines: false
  ignore:
    envs: []

cloudinary:
  cloud_name: judsonlmoore-com
  verbose: false
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always
    logo:
      min_width: 80
      max_width: 400
      fallback_max_width: 200
      steps: 3
      sizes: '(min-width: 50rem) 13rem, (min-width: 40rem) 25vw, 45vw'
      figure: never
      attributes:
        class: logo

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
