title: "Financing Biking" # the name of your site, e.g. ACME Corp.
tagline: "Finance an electric bike"
email: contact@financing.bike
description: >- # this means to ignore newlines until "baseurl:"
  Add description here
author: name
url: "https://financing.bike/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
#twitter:
#  username: 
#  card: summary #keep this to generate a twitter share card
permalink: pretty
gems:
  - jekyll-paginate-v2
  - jekyll-maps
plugins:
  - jekyll-feed
  - jekyll-money2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-datapage-generator
sass:
  sass_dir: assets/css
indlude:
  - _pages
  - _ebikes
  - _bike-shops
exclude: 
  - scrapy
collections:
  ebikes:
    output: true
  bike-shops:
    output: true
defaults:
  - scope:
      path: ''
    values:
      layout: page
  - scope:
      path: bike-shops
    values:
      layout: dealers-single
      permalink: /bike-shops/:title/
  - scope:
      path: assets/*
    values:
      sitemap: false
pagination:
  enabled: true
  per_page: 10
  permalink: /page-:num/
  title: :title
  limit: 0
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2
autopages:
  enabled: true
  collections:
    layouts:
      - srp
    title: ':coll'
    permalink: '/:coll/'
    slugify:
      mode: default
      case: true
  bike-shops:
    layouts:
      - shop-single
    title: ':coll'
    permalink: '/:coll/'
    slugify:
      mode: default
      case: true
compress_html:
  clippings: all
  comments:
    - '<!-- '
    - ' -->'
  endings:
    - html
    - head
    - body
    - li
    - dt
    - dd
    - rt
    - rp
    - optgroup
    - option
    - colgroup
    - caption
    - thead
    - tbody
    - tfoot
    - tr
    - td
    - th
  profile: false
  blanklines: false
  ignore:
    envs: []
page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: 'bikes'
    template: 'shop-single'
    name: 'name'
    dir: 'bikes'
cloudinary:
  cloud_name: judsonlmoore-com
  verbose: false
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always
    logo:
      min_width: 80
      max_width: 400
      fallback_max_width: 200
      steps: 3
      sizes: '(min-width: 50rem) 13rem, (min-width: 40rem) 25vw, 45vw'
      figure: never
      attributes:
        class: logo