title: "Critical Financing" # the name of your site, e.g. ACME Corp.
tagline: "Finance an electric bike"
email: your.email@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Add description here
author: name
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: UA-111111111-1
twitter:
  username: 
  card: summary #keep this to generate a twitter share card
permalink: pretty

# Build settings
gems:
  - jekyll-paginate-v2
plugins:
  - jekyll-feed
  - jekyll-money
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank

indlude:
  - _pages
  - _ebikes

sass:
  sass_dir: assets/css
      
compress_html:
  clippings: all
  comments:
    - '<!-- '
    - ' -->'
  endings:
    - html
    - head
    - body
    - li
    - dt
    - dd
    - rt
    - rp
    - optgroup
    - option
    - colgroup
    - caption
    - thead
    - tbody
    - tfoot
    - tr
    - td
    - th
  profile: false
  blanklines: false
  ignore:
    envs: []

cloudinary:
  cloud_name: judsonlmoore-com
  verbose: false
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always
    logo:
      min_width: 80
      max_width: 400
      fallback_max_width: 200
      steps: 3
      sizes: '(min-width: 50rem) 13rem, (min-width: 40rem) 25vw, 45vw'
      figure: never
      attributes:
        class: logo

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: ''
    values:
      layout: page
  - scope:
      path: _pages
    values:
      layout: bikes
      permalink: '/:basename'
      pagination: 
        enabled: "true"
  - scope:
      path: "_ebikes"
    values:
      layout: "bikes-single"
  - scope:
      path: "assets/*"
    values:
      sitemap: false


collections:
  ebikes:
    output: true


pagination:
  enabled: true
  per_page: 2
  permalink: '/page-:num/'
  title: ':title'
  limit: 0
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2
autopages:
  enabled: true
  categories:
    layouts:
      - bikes.html
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    slugify:
      mode: default
      case: true
  tags:
    layouts:
      - bikes.html
    title: 'Posts tagged with :tag'
    permalink: '/tag/:tag'
    slugify:
      mode: default
      case: true
  collections:
    layouts:
      - bikes.html
    title: 'Posts in collection :coll'
    permalink: '/:coll'
    slugify:
      mode: default
      case: true
  shop:
    layouts:
      - shop-single.html
    title: 'Products in category :coll'
    permalink: '/product/:coll'
    slugify:
      mode: default
      case: true

