title: "Financing Bike" # the name of your site, e.g. ACME Corp.
tagline: "Finance an electric bike"
email: contact@financing.bike
description: >- # this means to ignore newlines until "baseurl:"
  Add description here
author: name
url: "https://financing.bike" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
#twitter:
#  username: 
#  card: summary #keep this to generate a twitter share card
permalink: pretty
gems:
  - jekyll-paginate-v2
  - jekyll-maps
plugins:
  - jekyll-feed
  - jekyll-money2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank
sass:
  sass_dir: assets/css
indlude:
  - _pages
  - _posts
  - _bike-shops
exclude: 
  - scrapy
collections:
  ebikes:
    output: true
  bike-shops:
    output: true
defaults:
  - scope:
      path: ''
    values:
      layout: page
  - scope:
      path: bike-shops
    values:
      layout: dealers-single
      permalink: /bike-shops/:slug
  - scope:
      path: _posts/bikes
    values:
      layout: shop-single
      permalink: /:slugified_categories/:slug
  - scope:
      path: assets/*
    values:
      sitemap: false
pagination:
  enabled: true
  per_page: 10
#  permalink: /page-:num/
  title: :title
  sort_field: title
  sort_reverse: true
  trail:
    before: 2
    after: 2
autopages:
  enabled: true
  categories: 
    layouts: 
      - 'srp.html'
    title: ':cat'
    permalink: '/category/:cat'
    slugify:
      mode: 'pretty'
      case: true
  tags:
    layouts: 
      - 'srp.html'
    title: ':tag'
    permalink: '/tag/:tag'
    slugify:
      mode: 'pretty'
      case: true
  collections:
    layouts:
      - srp.html
    title: ':coll'
    permalink: '/:coll/'
    slugify:
      mode: 'pretty'
      case: true
compress_html:
  clippings: all
  comments:
    - '<!-- '
    - ' -->'
  endings:
    - html
    - head
    - body
    - li
    - dt
    - dd
    - rt
    - rp
    - optgroup
    - option
    - colgroup
    - caption
    - thead
    - tbody
    - tfoot
    - tr
    - td
    - th
  profile: false
  blanklines: false
  ignore:
    envs: []
cloudinary: # https://nhoizey.github.io/jekyll-cloudinary/
  cloud_name: judsonlmoore-com
  only_prod: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 1600
      steps: 5
      loading: lazy
    productImage:
      min_width: 343
      max_width: 738
      fallback_max_width: 738
      steps: 5
      attributes:
        class: d-block img-fluid
    productCarouselNavbar: 
      min_width: 125
      max_width: 250
      fallback_max_width: 250
      steps: 5
      attributes:
        class: nav-link d-block p-1 
        width: 125px
    srpProductImageVertical: 
      min_width: 125
      max_width: 250
      fallback_max_width: 250
      steps: 5
      attributes:
        class: mt-5 img-fluid
        width: 190px
    srpProductImageHorizontal: 
      min_width: 125
      max_width: 250
      fallback_max_width: 250
      steps: 5
      attributes:
        class: mt-3 img-fluid       