title: "BikeFi" # the name of your site, e.g. ACME Corp.
tagline: "Find deals across hundreds of online and local retailers of the world's best cycling products."
email: contact@bikefi.net
description: "BikeFi makes it easy for you to find the best deals on cycling products online and in your neighborhood."
author: BikeFi
url: "https://bikefi.net" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
incremental: true
#twitter:
#  username: 
#  card: summary #keep this to generate a twitter share card
permalink: pretty
plugins:
  - jekyll-include-cache
  - jekyll-paginate-v2
sass:
  sass_dir: assets/css
  style: compressed # possible values: nested expanded compact compressed
include: 
  - _product_tags
  - _product_categories
defaults:
  - scope:
      path: ''
    values:
      layout: page
  - scope:
      path: _posts/bike-shops
    values:
      layout: dealers-single
      permalink: /bike-shops/:slug/
  - scope:
      path: _posts/products
    values:
      layout: shop-single
      permalink: /:slug/
  - scope:
      path: assets/*
    values:
      sitemap: false
  - scope:
      path: _product_tags
    values:
      layout: srp
      sitemap: true
  - scope:
      path: _product_categories
    values:
      layout: srp
      sitemap: true
pagination:
  enabled: true
  per_page: 10
  permalink: "/page:num/"
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2
# autopages:
#   enabled: false
#   categories: 
#     layouts: 
#       - srp.html
#     title: :cat
#     permalink: /:cat/
#     slugify:
#       mode: default
#       case: true
#   tags:
#     layouts: 
#       - srp.html
#     title: :tag
#     permalink: /tag/:tag/
#     slugify:
#       mode: default
#       case: true
gtm-parameters: "?utm_source=bikefi.net&utm_medium=url&utm_campaign=friendly_neighborhood_spiderman" # https://ga-dev-tools.web.app/campaign-url-builder/
compress_html:
  clippings: all
  comments:
    - '<!-- '
    - ' -->'
  endings:
    - html
    - head
    - body
    - li
    - dt
    - dd
    - rt
    - rp
    - optgroup
    - option
    - colgroup
    - caption
    - thead
    - tbody
    - tfoot
    - tr
    - td
    - th
  profile: false
  blanklines: false
  ignore:
    envs: []
