title: "Critical Financing" # the name of your site, e.g. ACME Corp.
tagline: "Finance an electric bike"
email: your.email@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Add description here
author: name
url: "https://critical.financing.bike/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: UA-111111111-1
twitter:
  username: 
  card: summary #keep this to generate a twitter share card
permalink: pretty
gems:
  - jekyll-paginate-v2
  - jekyll-maps
plugins:
  - jekyll-feed
  - jekyll-money
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank
maps:
  google:
    api_key: 'AIzaSyBAwAykHUt0goZNODDdiVDU-7zcs34Ar8o'
sass:
  sass_dir: assets/css
indlude:
  - _pages
  - _ebikes
  - _dealers
collections:
  ebikes:
    output: true
  dealers:
    output: true
defaults:
  - scope:
      path: ''
    values:
      layout: page
  - scope:
      path: "_ebikes"
    values:
      layout: "shop-single"
      permalink: '/ebikes/:title/'
  - scope:
      path: "_dealers"
    values:
      layout: "dealers-single"
      permalink: '/dealers/:title/'
  - scope:
      path: "assets/*"
    values:
      sitemap: false
pagination:
  enabled: true
  per_page: 2
  permalink: '/page-:num/'
  title: ':title'
  limit: 0
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2
autopages:
  enabled: true
  collections:
    layouts:
      - shop.html
    title: ':coll'
    permalink: '/:coll/'
    slugify:
      mode: default
      case: true
  dealers:
    layouts:
      - dealers.html
    title: ':coll'
    permalink: '/:coll/'
    slugify:
      mode: default
      case: true
compress_html:
  clippings: all
  comments:
    - '<!-- '
    - ' -->'
  endings:
    - html
    - head
    - body
    - li
    - dt
    - dd
    - rt
    - rp
    - optgroup
    - option
    - colgroup
    - caption
    - thead
    - tbody
    - tfoot
    - tr
    - td
    - th
  profile: false
  blanklines: false
  ignore:
    envs: []
cloudinary:
  cloud_name: judsonlmoore-com
  verbose: false
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always
    logo:
      min_width: 80
      max_width: 400
      fallback_max_width: 200
      steps: 3
      sizes: '(min-width: 50rem) 13rem, (min-width: 40rem) 25vw, 45vw'
      figure: never
      attributes:
        class: logo