# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy

class ProductItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    variantsData = scrapy.Field()
    meta_description = scrapy.Field()
    meta_keywords = scrapy.Field()
    og_description = scrapy.Field()
    og_title = scrapy.Field()
    og_type = scrapy.Field()
    og_url = scrapy.Field()
    og_image = scrapy.Field()
    og_audio = scrapy.Field()
    og_determiner = scrapy.Field()
    og_locale = scrapy.Field()
    og_locale_alternate = scrapy.Field()
    og_site_name = scrapy.Field()
    og_video = scrapy.Field()
    og_image = scrapy.Field()
    og_image_secure_url = scrapy.Field()
    og_image_type = scrapy.Field()
    og_image_width = scrapy.Field()
    og_image_height = scrapy.Field()
    og_image_alt = scrapy.Field()
    og_video = scrapy.Field()
    og_video_secure_url = scrapy.Field()
    og_video_type = scrapy.Field()
    og_video_width = scrapy.Field()
    og_video_height = scrapy.Field()
    og_audio = scrapy.Field()
    og_audio_secure_url = scrapy.Field()
    og_audio_type = scrapy.Field()
    twitter_card = scrapy.Field()
    twitter_site = scrapy.Field()
    twitter_creator = scrapy.Field()
    twitter_image = scrapy.Field()
    twitter_title = scrapy.Field()
    id = scrapy.Field()
    make = scrapy.Field()
    model = scrapy.Field()
    brand_logo = scrapy.Field()
    product_name = scrapy.Field()
    star_rating = scrapy.Field()
    price_current = scrapy.Field()
    price_msrp = scrapy.Field()
    price_discount = scrapy.Field()
    availability = scrapy.Field()
    product_description = scrapy.Field()
    image = scrapy.Field()
    att1_title = scrapy.Field()
    att1_value = scrapy.Field()
    att2_title = scrapy.Field()
    att2_value = scrapy.Field()
    att3_title = scrapy.Field()
    att3_value = scrapy.Field()
    att4_title = scrapy.Field()
    att4_value = scrapy.Field()
    att5_title = scrapy.Field()
    att5_value = scrapy.Field()
    att6_title = scrapy.Field()
    att6_value = scrapy.Field()
    att7_title = scrapy.Field()
    att7_value = scrapy.Field()
    att8_title = scrapy.Field()
    att8_value = scrapy.Field()
    att9_title = scrapy.Field()
    att9_value = scrapy.Field()
    att10_title = scrapy.Field()
    att10_value = scrapy.Field()
    att11_title = scrapy.Field()
    att11_value = scrapy.Field()
    att12_title = scrapy.Field()
    att12_value = scrapy.Field()
    att13_title = scrapy.Field()
    att13_value = scrapy.Field()
    att14_title = scrapy.Field()
    att14_value = scrapy.Field()
    att15_title = scrapy.Field()
    att15_value = scrapy.Field()
    att16_title = scrapy.Field()
    att16_value = scrapy.Field()
    att17_title = scrapy.Field()
    att17_value = scrapy.Field()
    att18_title = scrapy.Field()
    att18_value = scrapy.Field()
    att19_title = scrapy.Field()
    att19_value = scrapy.Field()
    att20_title = scrapy.Field()
    att20_value = scrapy.Field()