name: Jekyll Deploy - Fast no deploy

on:
  push:
    branches:
      - fast 
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: standard
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1
      - name: Get latest data from Airtable
        run: sh ./.github/pulldata.sh ${{ secrets.AIRTABLE_KEY }} $GITHUB_BASE_REF 
      - name: troubleshoot
        run: |
          ls 
          ls **/_posts/
          echo $GITHUB_BASE_REF
      - name: Cache _site build
        uses: actions/cache@v2
        with:
          path: |
            ./_site
          key: ${{ runner.os }}-${{ hashFiles('**/_posts/*') }}
          restore-keys: ${{ runner.os }}-
      - name: ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1