name: Jekyll Deploy

on:
  push:
    branches:
      - main 
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: standard
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1
      - name: Bundler Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Get latest data from Airtable
        run: sh ./.github/pulldata.sh ${{ secrets.AIRTABLE_KEY }}
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
      - name: Exec jekyll algolia
        run: bundle exec jekyll algolia
        env:
          ALGOLIA_API_KEY: '${{ inputs.APIKEY }}'
      shell: bash
      - name: Rsync Deployments Action
        uses: Burnett01/rsync-deployments@5.2
        with:
          remote_user: 'launchsociety'
          remote_host: 'edpad.com'
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          path: './_site/*'
          remote_path: '/home/launchsociety/critical.financing.bike/'
          switches: '-avzr --delete'
