name: Jekyll Deploy

on:
  push:
    branches:
      - main 
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: standard
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1
      - name: Bundler Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Get latest data from Airtable
        run: sh ./.github/pulldata.sh 
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
      - name: Build & Deploy to Edvard DH
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: 'launchsociety'
          server: 'edpad.com'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './_site/*'
          remote_path: '/home/launchsociety/critical.financing.bike/'
          args: '-o ConnectTimeout=5'
