name: Jekyll Deploy

on:
  push:
    branches:
      - main 
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: standard
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1
      - name: Cache _site build
        uses: actions/cache@v2
        with:
          path: |
            ~/_site
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true
      - name: Get latest data from Airtable
        run: sh ./.github/pulldata.sh ${{ secrets.AIRTABLE_KEY }}
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
      - name: Rsync Deployments Action
        uses: Burnett01/rsync-deployments@5.2
        with:
          remote_user: 'dh_d468jd'
          remote_host: 'edpad.com'
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          path: './_site/*'
          remote_path: '/home/dh_d468jd/bikefi.net/'
          switches: '-avzr --delete'